swagger: '2.0'
info:
  title: Bank Argent - Transactions page API documentation
  description: Contains all available transactions page API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1/user
schemes:
  - http
# paths:
#   /user/profile/transactions/:accountId/:billId:
#   # /user/profile/transactions/:accountId/:billId:
#     put:
  # GET : les données du compte retournées sous forme d'objet : titre et objet d'objet pour les débits
  # PUT : le text input pour ajouter des notes sur un débit 
paths:
  /transactions/{accountId}:
    get:
      security:
        - Bearer: []
      tags:
        - account bills
      summary: Account Bills
      description: API for fetching bills from one account
      operationId: findBillsByAccount
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true      
        - name: accountId
          in: path
          description: ID of account bills to return
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Bills fetched successfully
          schema:
            type: array
            items: 
              $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error       
  /transactions/:accountId/{billsId}:
    get:
      security:
        - Bearer: []
      tags:
        - bills details
      summary: Bills Details
      description: ID of one bill detail to return
      operationId: findBillsDetailsById
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - name: accountId
          in: path
          description: ID of account bills to return
          required: false
          schema:
            type: string
        - name: bill_Id
          in: path
          description: bill ID to return
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Bill fetched successfully
          schema:
            $ref: '#/definitions/BillsResponse'
        '400':
          description: Invalid Fields
        '404':
          description: Bill not found
        '500':
          description: Internal Server Error 
    put:
      security:
        - Bearer: []
      tags:
        - bill notes
      summary: Update notes
      description: API to update one bill notes
      operationId: updateNotes
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - name: accountId
          in: path
          description: ID of account bills to return
          required: false
          schema:
            type: string
        - name: bill_Id
          in: path
          description: bill ID to return
          required: false
          schema:
            type: string
        - in: body
          name: body
          description: Update one bill note 
          required: true
          schema:
            $ref: '#/definitions/BillsResponse'
      produces:
        - application/json
      responses:
        '200':
          description: Bill successully updated
        '400':
          description: Invalid Fields
        '404':
          description: Bill not found
        '405':
          description: Invalid Input
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  BillsResponse:
    type: object
    properties:
      transactionType:
        type: string
      category:
        type: string
      notes: 
        type: string
  TransactionsResponse:
    type: object
    properties:
      date:
        type: string
      description: 
        type: string
      amount: 
        type: integer
      balance:
        type: integer
