swagger: '2.0'
info:
  title: Bank Argent - Transactions page API documentation
  description: Contains all available transactions page API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
# paths:
#   /user/profile/transactions/:accountId/:billId:
#   # /user/profile/transactions/:accountId/:billId:
#     put:
  # GET : les données du compte retournées sous forme d'objet : titre et objet d'objet pour les débits
  # PUT : le text input pour ajouter des notes sur un débit 
paths:
  /user/profile/transactions/:accountId:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transactions API
      description: API for fetching an user account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Account retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    get:
      tags:
        - User Module
      summary: Transactions
      description: Transactions for one account
      # no parameters for a get request, to be confirmed
      produces:
        - application/json
      responses:
        '200':
          description: Transactions fetched successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid URL
        '500':
          description: Internal Server Error
  /user/profile/transactions/:accountId/:billId:
    get:
      tags:
        - User Module
      summary: Bills
      description: API to load the bills with regards to one account
      produces:
        - application/json
      responses:
        '200':
          description: Bills fetched successfully
          schema:
            $ref: '#/definitions/BillsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error



  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          accountId:
            type: string
  TransactionsResponse:
    type: object
    properties:
      bills:
        type: object
        properties:
          bill:
            type: array
            properties:
              date:
                type: string
              description: 
                type: string
              amount: 
                type: integer
              balance:
                type: integer
  BillsResponse:
    type: object
    properties:
      transactionType:
        type: string
      category:
        type: string
      notes: 
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
